// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoLibreria.DataAccess;

namespace ProyectoLibreria.Migrations
{
    [DbContext(typeof(LibreriaDBContext))]
    partial class LibreriaDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Modern_Spanish_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProyectoLibreria.Models.DataModels.Autor", b =>
                {
                    b.Property<int>("IdAutor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Fech_defuncion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fech_naciminto")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nacionalidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAutor");

                    b.ToTable("Autores");
                });

            modelBuilder.Entity("ProyectoLibreria.Models.DataModels.Carrito", b =>
                {
                    b.Property<int>("IdCarrito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cantidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrecioTotal")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCarrito");

                    b.ToTable("Carritos");
                });

            modelBuilder.Entity("ProyectoLibreria.Models.DataModels.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("ProyectoLibreria.Models.DataModels.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaisId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCliente");

                    b.HasIndex("PaisId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("ProyectoLibreria.Models.DataModels.Comprobante", b =>
                {
                    b.Property<int>("IdComprobante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCarrito")
                        .HasColumnType("int");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<string>("ImporteTotal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomCliente")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdComprobante");

                    b.HasIndex("IdCarrito");

                    b.HasIndex("IdCliente");

                    b.ToTable("Comprobantes");
                });

            modelBuilder.Entity("ProyectoLibreria.Models.DataModels.Editorial", b =>
                {
                    b.Property<int>("IdEditorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Catalogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Continente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomAutores")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tematicas")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEditorial");

                    b.ToTable("Editoriales");
                });

            modelBuilder.Entity("ProyectoLibreria.Models.DataModels.Lenguaje", b =>
                {
                    b.Property<int>("IdLenguaje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EstadIdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FamLeng")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NivFluIdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegIdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipLeng")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdLenguaje");

                    b.ToTable("Lenguajes");
                });

            modelBuilder.Entity("ProyectoLibreria.Models.DataModels.Libro", b =>
                {
                    b.Property<int>("IdLibro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Anio_publi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CarritoIdCarrito")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdAutor")
                        .HasColumnType("int");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<int>("IdEditorial")
                        .HasColumnType("int");

                    b.Property<int>("IdLenguaje")
                        .HasColumnType("int");

                    b.Property<string>("Imglnk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Num_paginas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Precio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdLibro");

                    b.HasIndex("CarritoIdCarrito");

                    b.HasIndex("IdAutor");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdEditorial");

                    b.HasIndex("IdLenguaje");

                    b.ToTable("Libros");
                });

            modelBuilder.Entity("ProyectoLibreria.Models.DataModels.Opinion", b =>
                {
                    b.Property<int>("IdOpinion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Calificación")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaOpi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int?>("LibroIdLibro")
                        .HasColumnType("int");

                    b.Property<string>("Producto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoOpi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdOpinion");

                    b.HasIndex("IdCliente");

                    b.HasIndex("LibroIdLibro");

                    b.ToTable("Opiniones");
                });

            modelBuilder.Entity("ProyectoLibreria.Models.DataModels.Pais", b =>
                {
                    b.Property<int>("PaisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodIso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Continente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HusoHorario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Idioma")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Moneda")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomPais")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaisId");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("ProyectoLibreria.Models.DataModels.Cliente", b =>
                {
                    b.HasOne("ProyectoLibreria.Models.DataModels.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("ProyectoLibreria.Models.DataModels.Comprobante", b =>
                {
                    b.HasOne("ProyectoLibreria.Models.DataModels.Carrito", "Carrito")
                        .WithMany()
                        .HasForeignKey("IdCarrito")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoLibreria.Models.DataModels.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrito");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ProyectoLibreria.Models.DataModels.Libro", b =>
                {
                    b.HasOne("ProyectoLibreria.Models.DataModels.Carrito", null)
                        .WithMany("Libros")
                        .HasForeignKey("CarritoIdCarrito");

                    b.HasOne("ProyectoLibreria.Models.DataModels.Autor", "Autor")
                        .WithMany("Libros")
                        .HasForeignKey("IdAutor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoLibreria.Models.DataModels.Categoria", "Categoria")
                        .WithMany("Libros")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoLibreria.Models.DataModels.Editorial", "Editorial")
                        .WithMany("Libros")
                        .HasForeignKey("IdEditorial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoLibreria.Models.DataModels.Lenguaje", "Lenguaje")
                        .WithMany()
                        .HasForeignKey("IdLenguaje")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Categoria");

                    b.Navigation("Editorial");

                    b.Navigation("Lenguaje");
                });

            modelBuilder.Entity("ProyectoLibreria.Models.DataModels.Opinion", b =>
                {
                    b.HasOne("ProyectoLibreria.Models.DataModels.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoLibreria.Models.DataModels.Libro", null)
                        .WithMany("Opiniones")
                        .HasForeignKey("LibroIdLibro");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ProyectoLibreria.Models.DataModels.Autor", b =>
                {
                    b.Navigation("Libros");
                });

            modelBuilder.Entity("ProyectoLibreria.Models.DataModels.Carrito", b =>
                {
                    b.Navigation("Libros");
                });

            modelBuilder.Entity("ProyectoLibreria.Models.DataModels.Categoria", b =>
                {
                    b.Navigation("Libros");
                });

            modelBuilder.Entity("ProyectoLibreria.Models.DataModels.Editorial", b =>
                {
                    b.Navigation("Libros");
                });

            modelBuilder.Entity("ProyectoLibreria.Models.DataModels.Libro", b =>
                {
                    b.Navigation("Opiniones");
                });
#pragma warning restore 612, 618
        }
    }
}
